/**
 * Ratgeber-Cluster für thematische interne Verlinkung (nicht immer dieselben 4 Artikel).
 */

export type RatgeberCluster = {
  id: string;
  label: string;
  slugs: string[];
};

export const RATGEBER_CLUSTERS: RatgeberCluster[] = [
  {
    id: "gastronomie",
    label: "Gastronomie & Gewerbe",
    slugs: [
      "imbiss-ladenlokal-nutzungsaenderung-koeln",
      "eilbegehung-brandschutz-restaurant-gewerbe-koeln",
      "feuerloescher-gastronomie-koeln",
      "umbau-nutzungsaenderung-brandschutz",
      "verkaufsstaetten-rettungswege-sbauvo-nrw",
      "entrauchung-rauchableitung-bauo-sbauvo-nrw",
      "beherbergungsstaetten-hotel-sonderbau-nrw",
      "genehmigungsfrei-garage-freischank-bauo-nrw",
      "gaststaette-sonderbau-ungeregelt-nrw",
    ],
  },
  {
    id: "praxis",
    label: "Praxis & Medizin",
    slugs: [
      "arztpraxen-zusammenlegen-brandschutz-koeln",
      "praxis-umbau-brandschutz-koeln",
      "zwischenbescheid-brandschutz-bauamt-koeln",
      "kita-krankenhaus-sonderbau-ungeregelt-nrw",
    ],
  },
  {
    id: "umbau",
    label: "Umbau & Nutzungsänderung",
    slugs: [
      "umbau-nutzungsaenderung-brandschutz",
      "veranstaltung-gelegentliche-nutzungsaenderung-bauo-nrw",
      "sprinkler-trockenbau-nutzungsaenderung-bauo-nrw",
      "sprinkler-verzinkung-wasserstoffgefahr",
      "sprinkler-rueckbau-bma-nutzungsaenderung-koeln",
      "bestandsschutz-technische-sanierung-bauo-nrw",
      "abweichungen-paragraph-69-erlass-bauo-nrw",
      "lagerhalle-buero-umnutzung-koeln",
      "teilsanierung-buero-brandschutz-koeln",
      "feuerschutztueren-bestand-ertuechtigung-koeln",
      "rettungswegfenster-groesse-bestand-bauo-nrw",
      "feuerschutzabschluesse-bestand-nrw",
      "kraftstoff-lagerung-halle-garage-brandschutz",
      "raeume-brand-explosionsgefahr-bauo-nrw",
      "selbstentzuendung-putzlappen-metallspane",
      "technische-betriebsgebaeude-brandschutz-nrw",
      "modulbau-raumzellen-brandschutz-bauo-nrw",
      "heissarbeiten-brandwache-erlaubnisschein",
      "batteriespeicher-lithium-ionen-brandgefahren",
      "photovoltaik-brandrisiken-dach-anlage",
      "ladestation-stapler-brandgefahren",
      "industriebau-lagerhalle-indbaur-nrw",
      "feuerungsanlagen-feuvo-nrw-betrieb",
      "e-fahrzeuge-tiefgarage-brandgefahren-fbfhb-024",
      "trgs-800-brandschutz-gefahrstoffe-betrieb",
      "bauprodukte-ce-kennzeichnung-nrw",
      "mittelgrossgaragen-brandschutz-sbauvo-nrw",
      "genehmigungsfrei-garage-freischank-bauo-nrw",
      "elektrische-betriebsraeume-sbauvo-nrw",
      "brandmeldeanlage-wann-pflicht-sbauvo-nrw",
      "brandabschnitte-bauo-sbauvo-nrw",
      "rauchabschnitt-t30-rs-praxis-bauo-nrw",
      "sonderbau-bestand-gebaeude-sbauvo-nrw",
      "geeg-uvo-anlagentechnik-brandschutz-nrw",
      "grossraumbuero-sonderbau-ungeregelt-nrw",
    ],
  },
  {
    id: "betrieb",
    label: "Betrieb & Organisation",
    slugs: [
      "bestellung-brandschutzbeauftragter-nrw",
      "brandschutzordnung-pflicht-sbauvo-nrw",
      "brandschutzbeauftragter-pflicht-sbauvo-nrw",
      "aufgaben-brandschutzbeauftragter-koeln",
      "externer-brandschutzbeauftragter-koeln",
      "escape-room-brandschutzordnung-fluchtplan",
      "feuerwehrplan-fluchtplaene-pflicht-koeln",
      "feuerwehrplaene-wann-pflicht-sbauvo-nrw",
      "feuerloescher-gastronomie-koeln",
      "brandschau-koeln-feuerwehr",
      "eilbegehung-brandschutz-restaurant-gewerbe-koeln",
      "prueffristen-brandschutz-dguv-205-040-ueberblick",
      "bma-prueffristen-brandmeldeanlage",
      "brandbegrenzungsdecken-lithiumbatterie",
      "batteriespeicher-lithium-ionen-brandgefahren",
      "co2-feuerloescher-raeume-erstickungsgefahr",
      "brandschutz-gemeinschaftsunterkuenfte",
      "alarmierung-evakuierung-betrieb",
      "brandschutzhelfer-ausbildung-anforderungen",
      "leichtschaum-loeschanlagen-personenschutz",
      "aerosol-loeschanlagen-personenschutz",
      "loeschgas-loeschanlagen-personenschutz",
      "selbstentzuendung-putzlappen-metallspane",
      "pulver-loeschanlagen-personenschutz",
      "betrieblicher-brandschutz-praxis-ueberblick",
      "heissarbeiten-brandwache-erlaubnisschein",
      "brandgase-rauch-brandfall",
      "brandursachen-betrieb-praevention",
      "batteriespeicher-lithium-ionen-brandgefahren",
      "sonderbau-anlagen-pruefung-maengel-nrw",
      "fehlalarme-brandmeldeanlage-mehrfachsensor",
      "sprinkler-verzinkung-wasserstoffgefahr",
      "feuerloescher-entsorgung-pfas-abfall",
      "spezial-loeschanlagen-gefaehrdungsbeurteilung",
      "photovoltaik-brandrisiken-dach-anlage",
      "ladestation-stapler-brandgefahren",
      "versammlungsstaetten-betrieb-sbauvo-nrw",
      "explosionsschutz-brandschutz-schnittstelle",
      "pruefvo-nrw-wiederkehrende-pruefung-sonderbau",
      "trgs-800-brandschutz-gefahrstoffe-betrieb",
      "feuerungsanlagen-feuvo-nrw-betrieb",
      "e-fahrzeuge-tiefgarage-brandgefahren-fbfhb-024",
      "dguv-205-001-gefaehrdungsbeurteilung-brandschutz",
      "bma-brandfallsteuerung-aufzug-sbauvo-nrw",
      "aufzuege-brandschutz-bauo-sbauvo-nrw",
      "brandmeldeanlage-wann-pflicht-sbauvo-nrw",
      "loeschwasser-rueckhalt-konzept-nrw",
      "loeschwasserversorgung-hydranten-verkehrsflaeche-dvgw-w405",
      "fluktuationshaus-evakuierung-nrw",
      "brandschutzuebung-betrieb-nrw",
      "brandschutz-dokumentation-betrieb-nrw",
      "wassergefaehrdende-stoffe-lager-lau-nrw",
      "hochhaus-betriebsvorschriften-sbauvo-nrw",
    ],
  },
  {
    id: "plaene-bso",
    label: "Pläne & Brandschutzordnung",
    slugs: [
      "alarmierung-evakuierung-betrieb",
      "brandschutz-gemeinschaftsunterkuenfte",
      "modulbau-raumzellen-brandschutz-bauo-nrw",
      "escape-room-brandschutzordnung-fluchtplan",
      "brandschutzordnung-pflicht-sbauvo-nrw",
      "feuerwehrplan-fluchtplaene-pflicht-koeln",
      "feuerwehrplaene-wann-pflicht-sbauvo-nrw",
      "feuerwehrzufahrten-bewegungsflaechen-bauo-sbauvo-nrw",
      "fluchtplan-feuerwehrplan-aktualisieren-gewerbe",
      "flucht-und-rettungswege-bauo-nrw",
      "leitungsanlagen-bauo-sbauvo-nrw",
      "notwendige-treppen-treppenraeume-bauo-sbauvo-nrw",
      "entrauchung-rauchableitung-bauo-sbauvo-nrw",
      "brandmeldeanlage-wann-pflicht-sbauvo-nrw",
      "brandabschnitte-bauo-sbauvo-nrw",
      "brandlasten-notwendige-flure-bauo-nrw",
      "waende-notwendige-flure-bauo-nrw",
      "sicherheitsstromversorgung-wann-pflicht-sbauvo-nrw",
      "sicherheitsbeleuchtung-wann-pflicht-sbauvo-nrw",
      "rettungswegfenster-groesse-bestand-bauo-nrw",
      "raeume-brand-explosionsgefahr-bauo-nrw",
      "tuerarten-brandschutz-bauo-nrw",
      "zweiter-rettungsweg-innenhof-bauo-nrw",
      "aufgaben-brandschutzbeauftragter-koeln",
      "brandschutzbeauftragter-pflicht-sbauvo-nrw",
      "betrieblicher-brandschutz-praxis-ueberblick",
      "versammlungsstaetten-betrieb-sbauvo-nrw",
      "versammlungsstaetten-baulich-sbauvo-nrw",
      "feuerwehrzufahrt-bewegungsflaeche-sbauvo-nrw",
      "pflegeeinrichtung-sonderbau-nrw",
      "fluktuationshaus-evakuierung-nrw",
      "mehrzweckhallen-sportstaetten-sbauvo-nrw",
      "sportstadien-blockbildung-sbauvo-nrw",
      "feuerwehrzufahrten-bewegungsflaechen-bauo-sbauvo-nrw",
      "feuerwehrzufahrt-bewegungsflaeche-sbauvo-nrw",
      "feuerwehrzufahrt-zugaenge-runderlass-bauo-nrw",
      "aufstell-bewegungsflaeche-strasse-hubrettung-bauo-nrw",
      "brandsicherheitswache-veranstaltung-sbauvo-nrw",
      "veranstaltung-gelegentliche-nutzungsaenderung-bauo-nrw",
    ],
  },
  {
    id: "behoerde",
    label: "Behörde & Genehmigung Köln",
    slugs: [
      "bauaufsicht-unterlagen-koeln",
      "brandschutzfachplaner-rollen-bauo-nrw",
      "bauantrag-brandschutz-unterlagen-koeln",
      "feuerwehr-abstimmung-vor-bauamt-bauo-nrw",
      "feuerwehrzufahrten-bewegungsflaechen-bauo-sbauvo-nrw",
      "feuerwehrzufahrt-zugaenge-runderlass-bauo-nrw",
      "aufstell-bewegungsflaeche-strasse-hubrettung-bauo-nrw",
      "brandschau-koeln-feuerwehr",
      "zwischenbescheid-brandschutz-bauamt-koeln",
      "modulbau-raumzellen-brandschutz-bauo-nrw",
      "abweichungen-paragraph-69-erlass-bauo-nrw",
      "beseitigungsverfuegung-brandschutz-abweichung-bauo-nrw",
      "rettungswegfenster-groesse-bestand-bauo-nrw",
      "zweiter-rettungsweg-innenhof-bauo-nrw",
      "zweiter-rettungsweg-dachfenster-bauo-nrw",
      "loeschwasser-hydranten-gewerbe-koeln",
      "loeschwasserversorgung-hydranten-verkehrsflaeche-dvgw-w405",
      "brandschutzberatung-koeln-auflagen-risiken",
      "brandschutzkonzept-baupruefvo-nrw",
      "feuerwehrzufahrt-bewegungsflaeche-sbauvo-nrw",
      "genehmigungsfrei-garage-freischank-bauo-nrw",
      "loeschwasser-rueckhalt-konzept-nrw",
      "brandschutznachweis-din-18230-nrw",
      "gebaeudeklassen-grenzfaelle-nrw",
    ],
  },
  {
    id: "baustelle",
    label: "Baustelle & Abnahme",
    slugs: [
      "fachbauleitung-brandschutz-baustelle-koeln",
      "leitungsanlagen-bauo-sbauvo-nrw",
      "abschottungen-durchbrueche-baustelle-koeln",
      "brandschutz-abnahme-nach-umbau-koeln",
      "feuerloescher-baustelle-asr-a22",
      "heissarbeiten-brandwache-erlaubnisschein",
      "bauprodukte-ce-kennzeichnung-nrw",
      "baupavo-nrw-bauarten-verwendbarkeitsnachweis",
    ],
  },
  {
    id: "feuerloescher",
    label: "Feuerlöscher & ASR A2.2",
    slugs: [
      "loeschmitteleinheiten-feuerloescher-arbeitsplatz-asr-a22",
      "brandklassen-loeschertypen-feuerloescher-din-en-2",
      "feuerloescher-pruefen-wartung-asr-a22",
      "feuerloescher-richtig-loeschen-technik",
      "brandschutzhelfer-ausbildung-anforderungen",
      "feuerloescher-baustelle-asr-a22",
      "feuerloescher-gastronomie-koeln",
      "co2-feuerloescher-raeume-erstickungsgefahr",
      "feuerloescher-entsorgung-pfas-abfall",
      "brandgase-rauch-brandfall",
    ],
  },
  {
    id: "prueffristen",
    label: "Prüffristen im Brandschutz",
    slugs: [
      "prueffristen-brandschutz-dguv-205-040-ueberblick",
      "wer-darf-brandschutzanlagen-pruefen",
      "wartung-inspektion-pruefung-brandschutz-din-31051",
      "pruefpflichten-sonderbauten-muster-pruefverordnung",
      "bma-prueffristen-brandmeldeanlage",
      "feuerschutzabschluesse-prueffristen-fstA",
      "rwa-entrauchung-prueffristen",
      "entrauchung-rauchableitung-bauo-sbauvo-nrw",
      "sprinkler-loeschanlagen-prueffristen",
      "sprinkler-verzinkung-wasserstoffgefahr",
      "leichtschaum-loeschanlagen-personenschutz",
      "aerosol-loeschanlagen-personenschutz",
      "loeschgas-loeschanlagen-personenschutz",
      "pulver-loeschanlagen-personenschutz",
      "feuerloescher-pruefen-wartung-asr-a22",
      "sonderbau-anlagen-pruefung-maengel-nrw",
      "fehlalarme-brandmeldeanlage-mehrfachsensor",
      "spezial-loeschanlagen-gefaehrdungsbeurteilung",
      "pruefvo-nrw-wiederkehrende-pruefung-sonderbau",
      "hochhaus-brandschutz-sbauvo-nrw",
      "feuerwehrplaene-wann-pflicht-sbauvo-nrw",
      "sicherheitsstromversorgung-wann-pflicht-sbauvo-nrw",
      "sicherheitsbeleuchtung-wann-pflicht-sbauvo-nrw",
      "raeume-brand-explosionsgefahr-bauo-nrw",
      "hochhaus-betriebsvorschriften-sbauvo-nrw",
      "hochhaus-entrauchung-sbauvo-nrw",
      "bma-brandfallsteuerung-aufzug-sbauvo-nrw",
      "brandmeldeanlage-wann-pflicht-sbauvo-nrw",
    ],
  },
  {
    id: "brandschadensanierung",
    label: "Brandschadensanierung (VdS 2357)",
    slugs: [
      "brandschadensanierung-ueberblick-vds-2357",
      "gefahrenbereiche-brandschadensanierung-vds-2357",
      "ablauf-brandschadensanierung-vds-2357",
      "aufgaben-auftraggeber-brandschadensanierung",
      "gefaehrdungsbeurteilung-sofortmassnahmen-brandschadensanierung",
      "arbeitssicherheitsplan-brandschadensanierung",
      "ausfuehrendes-unternehmen-brandschadensanierung-dguv",
      "entsorgung-schutzmassnahmen-brandschadensanierung",
    ],
  },
  {
    id: "nrw-grundlagen",
    label: "BauO NRW Grundlagen",
    slugs: [
      "gebaeudeklassen-brandschutz-bauo-nrw",
      "gesetzliche-einstufung-gebaeude-bauo-nrw",
      "brandschutzordnung-pflicht-sbauvo-nrw",
      "brandschutzbeauftragter-pflicht-sbauvo-nrw",
      "aufzuege-brandschutz-bauo-sbauvo-nrw",
      "mittelgrossgaragen-brandschutz-sbauvo-nrw",
      "elektrische-betriebsraeume-sbauvo-nrw",
      "leitungsanlagen-bauo-sbauvo-nrw",
      "notwendige-treppen-treppenraeume-bauo-sbauvo-nrw",
      "entrauchung-rauchableitung-bauo-sbauvo-nrw",
      "gebaeudeklasse-1-2-brandschutz-bauo-nrw",
      "gebaeudeklasse-3-brandschutz-bauo-nrw",
      "gebaeudeklasse-4-brandschutz-bauo-nrw",
      "gebaeudeklasse-5-brandschutz-bauo-nrw",
      "tuerarten-brandschutz-bauo-nrw",
      "flucht-und-rettungswege-bauo-nrw",
      "leitungsanlagen-bauo-sbauvo-nrw",
      "notwendige-treppen-treppenraeume-bauo-sbauvo-nrw",
      "brandmeldeanlage-wann-pflicht-sbauvo-nrw",
      "brandabschnitte-bauo-sbauvo-nrw",
      "feuerwehrzufahrten-bewegungsflaechen-bauo-sbauvo-nrw",
      "brandlasten-notwendige-flure-bauo-nrw",
      "rettungswegfenster-groesse-bestand-bauo-nrw",
      "waende-notwendige-flure-bauo-nrw",
      "zweiter-rettungsweg-innenhof-bauo-nrw",
      "veranstaltung-gelegentliche-nutzungsaenderung-bauo-nrw",
      "feuerwehrzufahrt-zugaenge-runderlass-bauo-nrw",
      "aufstell-bewegungsflaeche-strasse-hubrettung-bauo-nrw",
      "sonderbauten-brandschutz",
      "raeume-brand-explosionsgefahr-bauo-nrw",
      "sonderbauten-geregelt-ungeregelt-bauo-nrw",
      "brandschutzkonzept-wann-noetig",
      "brandschutzfachplaner-rollen-bauo-nrw",
      "bestandsschutz-technische-sanierung-bauo-nrw",
      "abweichungen-paragraph-69-erlass-bauo-nrw",
      "flucht-und-rettungswege-bauo-nrw",
      "betrieblicher-brandschutz-praxis-ueberblick",
      "brandursachen-betrieb-praevention",
      "sonderbau-anlagen-pruefung-maengel-nrw",
      "versammlungsstaetten-betrieb-sbauvo-nrw",
      "explosionsschutz-brandschutz-schnittstelle",
      "industriebau-lagerhalle-indbaur-nrw",
      "pruefvo-nrw-wiederkehrende-pruefung-sonderbau",
      "trgs-800-brandschutz-gefahrstoffe-betrieb",
      "feuerungsanlagen-feuvo-nrw-betrieb",
      "e-fahrzeuge-tiefgarage-brandgefahren-fbfhb-024",
      "bauprodukte-ce-kennzeichnung-nrw",
      "schulen-schulbaurichtlinie-nrw",
      "pflegeeinrichtung-sonderbau-nrw",
      "mittelgrossgaragen-brandschutz-sbauvo-nrw",
      "hochhaus-brandschutz-sbauvo-nrw",
      "aufzuege-brandschutz-bauo-sbauvo-nrw",
      "brandschutzkonzept-baupruefvo-nrw",
      "verkaufsstaetten-rettungswege-sbauvo-nrw",
      "beherbergungsstaetten-hotel-sonderbau-nrw",
      "versammlungsstaetten-baulich-sbauvo-nrw",
      "feuerwehrzufahrt-bewegungsflaeche-sbauvo-nrw",
      "genehmigungsfrei-garage-freischank-bauo-nrw",
      "elektrische-betriebsraeume-sbauvo-nrw",
      "kita-krankenhaus-sonderbau-ungeregelt-nrw",
      "baupavo-nrw-bauarten-verwendbarkeitsnachweis",
      "modulbau-raumzellen-brandschutz-bauo-nrw",
      "mehrzweckhallen-sportstaetten-sbauvo-nrw",
      "hochhaus-betriebsvorschriften-sbauvo-nrw",
      "sonderbau-bestand-gebaeude-sbauvo-nrw",
      "gaststaette-sonderbau-ungeregelt-nrw",
      "grossraumbuero-sonderbau-ungeregelt-nrw",
      "brandmeldeanlage-wann-pflicht-sbauvo-nrw",
      "brandabschnitte-bauo-sbauvo-nrw",
      "rauchabschnitt-t30-rs-praxis-bauo-nrw",
      "bma-brandfallsteuerung-aufzug-sbauvo-nrw",
      "brandmeldeanlage-wann-pflicht-sbauvo-nrw",
      "loeschwasser-rueckhalt-konzept-nrw",
      "loeschwasserversorgung-hydranten-verkehrsflaeche-dvgw-w405",
      "feuerwehrplaene-wann-pflicht-sbauvo-nrw",
      "sicherheitsstromversorgung-wann-pflicht-sbauvo-nrw",
      "sicherheitsbeleuchtung-wann-pflicht-sbauvo-nrw",
      "geeg-uvo-anlagentechnik-brandschutz-nrw",
      "fluktuationshaus-evakuierung-nrw",
      "gebaeudeklassen-grenzfaelle-nrw",
      "sportstadien-blockbildung-sbauvo-nrw",
      "feuerwehrzufahrt-bewegungsflaeche-sbauvo-nrw",
      "feuerwehrzufahrt-zugaenge-runderlass-bauo-nrw",
      "aufstell-bewegungsflaeche-strasse-hubrettung-bauo-nrw",
      "brandsicherheitswache-veranstaltung-sbauvo-nrw",
      "brandschutznachweis-din-18230-nrw",
      "hochhaus-entrauchung-sbauvo-nrw",
      "wassergefaehrdende-stoffe-lager-lau-nrw",
    ],
  },
];

const slugToClusterId = new Map<string, string>();
for (const cluster of RATGEBER_CLUSTERS) {
  for (const slug of cluster.slugs) {
    if (!slugToClusterId.has(slug)) {
      slugToClusterId.set(slug, cluster.id);
    }
  }
}

/** Cluster-Peers für einen Artikel (ohne sich selbst), max. limit. */
export function getClusterPeerSlugs(currentSlug: string, limit = 4): string[] {
  const clusterId = slugToClusterId.get(currentSlug);
  if (!clusterId) return [];

  const cluster = RATGEBER_CLUSTERS.find((c) => c.id === clusterId);
  if (!cluster) return [];

  return cluster.slugs.filter((s) => s !== currentSlug).slice(0, limit);
}

export function getClusterLabel(currentSlug: string): string | undefined {
  const clusterId = slugToClusterId.get(currentSlug);
  if (!clusterId) return undefined;
  return RATGEBER_CLUSTERS.find((c) => c.id === clusterId)?.label;
}
